# unique(x) 

In [ ]:
compute the sorted, unique elements in x

In [27]:
import numpy as np


In [28]:
a = np.random.randint(1, 10, size=20) # length = 20 elements from 1 to 9.
a

array([6, 8, 4, 8, 9, 7, 1, 2, 6, 3, 8, 8, 5, 1, 6, 2, 2, 1, 1, 9])

In [29]:
np.unique(a) # for practical example in one Aplication(account,i.e like facebook or finincial account transaction)  how many users login into account in per day. 

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# in1d(x, y)
 

In [ ]:
# compute a boolean array indicating whether each element of x id contained in y

In [23]:
a = np.random.randint(1, 10, size=20) # for this arrays practical example is that there are 20 accounts in banks but we want only 05 account will be check with ID from these 20 accounts.then its results in true and false statements.
b = np.random.randint(1, 10, size=5)                   
print(a,b, sep='\n')
[True if x in a else False for x in b]

[5 6 6 6 2 6 6 6 7 4 6 9 1 2 6 3 3 9 8 8]
[5 4 7 7 8]


[True, True, True, True, True]

In [25]:
a = np.random.randint(1, 10, size=20) # now another example we want these 05 users data then its return the data with true and false statements.
b = np.random.randint(1, 10, size=5)                   
print(a,b, sep='\n')

np.in1d(b, a)


[8 5 3 9 1 5 9 7 2 4 7 1 8 6 3 2 3 3 1 5]
[9 1 6 5 9]


array([ True,  True,  True,  True,  True])

# Intersect1d

In [33]:
print(a, b, sep='\n') # Intersect1d sample gives the two same values.
np.intersect1d(b, a)

[5 3 7 1 6 5 6 8 3 9 6 8 8 1 8 1 7 8 6 6]
[4 6 7 9 2]


array([6, 7, 9])

# Setdiff1d

In [37]:
a = np.random.randint(1, 10, size=20) # its give the value which one not in b from a.its mean difference values  in both elements
b = np.random.randint(1, 10, size=5)  # its given the account which is not found,means that ID users is not avaible accounts.
print(a,b, sep='\n')
np.setdiff1d(b, a)

[8 8 1 5 6 2 6 4 6 7 7 6 3 3 7 7 3 6 5 5]
[3 1 8 3 9]


array([9])

# XOR


In [39]:
# 0 0 ->0 # in practical example which user ID LOGIN in two or three months (jan,feb)
# 0 1 ->1
# 1 0 ->1
# 1 1 ->0
print(a,b, sep='\n')
np.setxor1d(b,a)

[8 8 1 5 6 2 6 4 6 7 7 6 3 3 7 7 3 6 5 5]
[3 1 8 3 9]


array([2, 4, 5, 6, 7, 9])

In [4]:
a = np.arange(2*2*2).reshape(2,2,2)
print(a)
np.dsplit(a,2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]),
 array([[[1],
         [3]],
 
        [[5],
         [7]]])]

In [7]:
a = np.arange(2*2*2).reshape(2,2,2)
print(a)
np.split(a, 2, axis=2)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0],
         [2]],
 
        [[4],
         [6]]]),
 array([[[1],
         [3]],
 
        [[5],
         [7]]])]

In [ ]:
# axis 0 = works same like before sequence divide from top to bottom,for example first row separate second row separate and third row will be separate.
# axis 1 = its breaks the coloums wise,if you want break  left to right then 1.
# 

In [13]:
a = np.arange(2*2*2).reshape(2,2,2)
print(a)
np.dsplit(a,1)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


[array([[[0, 1],
         [2, 3]],
 
        [[4, 5],
         [6, 7]]])]