# Basic Indexing and Slicing

NumPY array indexing is a rich topic,as there are many ways you may want to select a subset of your data or individual elements.One -dimensional  arrays are simple, on the surface they act similarly to python list:

In [2]:
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[7]

7

In [4]:
arr[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [5]:
arr[2:6]

array([2, 3, 4, 5])

In [8]:
arr[2:6] = 34
arr

array([ 0,  1, 34, 34, 34, 34,  6,  7,  8,  9])

If you  assign a scalar value to a slice,as in arr[2:6] = 34 the value is propagated(or broadcasted henceforth) to the entire selection.
This mean that the data is not copied, and any modifications to the view will be reflected in the source array.
To give an example of this,I first create a slice of arr:

In [9]:
arr_slice = arr[2:6]
arr_slice

array([34, 34, 34, 34])

Now, when i change values in arr_slice, the mutations are reflected in the original array arr:

In [10]:
arr_slice[1] =12345
arr_slice

array([   34, 12345,    34,    34])

In [11]:
arr

array([    0,     1,    34, 12345,    34,    34,     6,     7,     8,
           9])

The "bare" slice[:] will assign to all values in an array:

In [12]:
arr_slice[:] = 55

arr

array([ 0,  1, 55, 55, 55, 55,  6,  7,  8,  9])

If you want a copy of a slice of an ndarray instead of a view,you will need to explicitly copy the array for example,
arr[2:6].copy()

In [13]:
arr[2:6].copy()
arr

array([ 0,  1, 55, 55, 55, 55,  6,  7,  8,  9])

With higher dimensional arrays, you have many more options,In a two-dimenstional array,the elements at each index are no longer scalars but rather one-dimensional arrays:

In [15]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
arr2d[1]

array([4, 5, 6])

Thus,individual elements can be accessed recursively.But that is a bit too much work,so you can pass a comma-separated list of indices to select individual elements.so these are equivalent:

In [19]:
arr2d[1][1]

5

In [20]:
arr2d[1,1]

5

In multidimensional arrays, if you omit later indices, the retruned object will be a lower dimensional ndarray consisting of all data along the higher dimensions.So in the 2  2  3 array arr3d:
    

In [24]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

Both scalar values and arrays can be assigned to arr3d[0]:

In [ ]:
# old_values = arr3d[0].copy()
arr3d[0] = 42
arr3d

In [30]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Similarly,arr3d[1,0] gives you all of the values whose indices start with(1,0),forming a 1-dimensional array:


In [31]:
arr3d[1,0]

array([7, 8, 9])

This expression is the same as though we had indexed in two steps:

In [32]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [33]:
x[0]

array([7, 8, 9])

Note that in all of these cases where subsections of the array have been selected,the returned arrays are view.

# Indexing with slices
Like one-dimensional objects such as python lists, ndarrays can be sliced with the familiar syntax:

In [34]:
arr

array([ 0,  1, 22, 55, 55, 55,  6,  7,  8,  9])

In [35]:
arr[1:6]

array([ 1, 22, 55, 55, 55])

Consider the two-dimensional array from before, arr2d.Slicing this array is a bit different:

In [36]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

As you can see, it has sliced along axis 0,the first axis. A slice, therefore, selects a range of elements along an axis.It can be helpful to read the expression arr2d[:2] as "select the first two rows of arr2d".

you can pass multiple slices just like you can pass multiple indexes:

In [38]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

When slicing like this, you always obtain array views of the same number of dimensions.By mixing integer indexes and slices, you get lower dimensional slices.for example, I can select the second row but only the first two columns like so:

In [39]:
arr2d[1, :2]

array([4, 5])

Similarly, I can select the third column but only the first two rows like so:

In [40]:
arr2d[:2, 2]

array([3, 6])

In [41]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

Note that a colon by itself means to take the entire axis,so you can slice only higher dimensional axes by doing:

In [42]:
arr2d[:, :]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Of course,assigning to a slice expression assigns to the whole selection:

In [44]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])