# Stacking

In [3]:
import numpy as np
# Join a sequence of arrays along a new  axis.
a = np.arange(9).reshape(3,3)
b = np.arange(9,18).reshape(3,3)
print(a)
print('=============')
print(b)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]


In [4]:
np.stack((a,b))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]])

In [33]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [34]:
arr2 = np.array([4,5,6])
arr2

array([4, 5, 6])

In [37]:
arr = np.stack((arr1,arr2))
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
np.stack((arr1,arr2),axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

# Horizontal Stacking

In [5]:
# combines two arrays in a manner where the colums of the second array are placed to the right of those in the first array.The 
# function actually stacks the 
# two items provided in a two-element tuple.The result is a new array with data copied from the two that are specified:

arr1= np.arange(16).reshape(8,2)
arr1

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [6]:
arr2 = np.arange(16,56).reshape(8,5)
arr2

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50],
       [51, 52, 53, 54, 55]])

In [8]:
np.hstack((arr1,arr2))

array([[ 0,  1, 16, 17, 18, 19, 20],
       [ 2,  3, 21, 22, 23, 24, 25],
       [ 4,  5, 26, 27, 28, 29, 30],
       [ 6,  7, 31, 32, 33, 34, 35],
       [ 8,  9, 36, 37, 38, 39, 40],
       [10, 11, 41, 42, 43, 44, 45],
       [12, 13, 46, 47, 48, 49, 50],
       [14, 15, 51, 52, 53, 54, 55]])

In [9]:
np.hstack((arr2,arr1))

array([[16, 17, 18, 19, 20,  0,  1],
       [21, 22, 23, 24, 25,  2,  3],
       [26, 27, 28, 29, 30,  4,  5],
       [31, 32, 33, 34, 35,  6,  7],
       [36, 37, 38, 39, 40,  8,  9],
       [41, 42, 43, 44, 45, 10, 11],
       [46, 47, 48, 49, 50, 12, 13],
       [51, 52, 53, 54, 55, 14, 15]])

In [10]:
np.concatenate((arr1,arr2), axis = 1) # similar to hstack

array([[ 0,  1, 16, 17, 18, 19, 20],
       [ 2,  3, 21, 22, 23, 24, 25],
       [ 4,  5, 26, 27, 28, 29, 30],
       [ 6,  7, 31, 32, 33, 34, 35],
       [ 8,  9, 36, 37, 38, 39, 40],
       [10, 11, 41, 42, 43, 44, 45],
       [12, 13, 46, 47, 48, 49, 50],
       [14, 15, 51, 52, 53, 54, 55]])

# Vertical Stacking

In [11]:
# Vertical stacking returns a new array with the contents of the second array as appended rows of the array.

arr3 = np.arange(20).reshape(2,10)
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [12]:
arr4 = np.arange(20,60).reshape(4,10)
arr4

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [16]:
arr5 = np.arange(20,60).reshape(4,10)

In [17]:
np.vstack((arr3,arr4,arr5))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [18]:
np.concatenate((arr3,arr4,arr5), axis = 0)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [44]:
# Join two 2-D Arrays along rows(axis = 1):
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr1

array([[1, 2],
       [3, 4]])

In [45]:
arr2 = np.array([[5,6],[7,8]])
arr2

array([[5, 6],
       [7, 8]])

In [46]:
np.concatenate((arr1,arr2), axis = 1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [47]:
np.concatenate((arr1,arr2))

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [48]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

In [49]:
arr2 = np.array([4,5,6])
arr2

array([4, 5, 6])

In [50]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])

# Depth Stacking

In [57]:
arr5 = np.arange(9).reshape(3,3)
arr5

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
arr6 = np.arange(9,18).reshape(3,3)
arr6

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [63]:
np.dstack((arr5,arr6))

array([[[ 0,  9],
        [ 1, 10],
        [ 2, 11]],

       [[ 3, 12],
        [ 4, 13],
        [ 5, 14]],

       [[ 6, 15],
        [ 7, 16],
        [ 8, 17]]])

In [67]:
x = np.array((13, 15, 17))
y = np.array((5, 7, 9))
print(np.dstack((x,y)).shape)
np.dstack((x,y))

(1, 3, 2)


array([[[13,  5],
        [15,  7],
        [17,  9]]])

# Numpy Splitting Array
Array can also be split into multiple arrrays along the horizontal, vertical and depth axes using the np.hsplit() functions.we will only look at the np.hsplit() function as teh others work similarly.


In [51]:
arr = np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [52]:
newarr = np.array_split(arr,3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [53]:
# Split the array in 4 parts:

arr = np.array([1,2,3,4,5,6])

newarr = np.array_split(arr,4)
newarr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [55]:
# We also have the method split() available but it will not adjust the elements when elements are less in source array for splitting like in example above, array_split() worked properly but split() would fail.

newarr = np.split(arr,4)

newarr

ValueError: array split does not result in an equal division

In [69]:
x = np.arange(9.0)
print(x)
print("=============")
np.split(x,2)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


ValueError: array split does not result in an equal division

In [70]:
x = np.arange(9.0)
print(x)
print("=============")
np.split(x,3)

[0. 1. 2. 3. 4. 5. 6. 7. 8.]


[array([0., 1., 2.]), array([3., 4., 5.]), array([6., 7., 8.])]

In [72]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [73]:
# horiz split the 2-d array into 4 array columns
np.hsplit(a,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [74]:
# horiz split the 2-d array into 2 array columns
np.hsplit(a,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [75]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [76]:
# horiz split the 2-d array into 2 array columns
np.vsplit(a,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [77]:
# split at columns 1 and 3

np.hsplit(a,[1, 3])

[array([[0],
        [4],
        [8]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3],
        [ 7],
        [11]])]

# Useful numerical methods of NumPY arrays

In [78]:
# demonstrate some of the properties of NumPY arrays
m = np.arange(10,19).reshape(3,3)
print(m)

[[10 11 12]
 [13 14 15]
 [16 17 18]]


In [79]:
print ("{0} min of the entire matrix" .format(m.min()))
print ("{0} max of entire matrix" .format(m.max())) 
print ("{0} position of the min value" .format(m.argmin())) # index of the min value
print ("{0} position of the max value" .format(m.argmax())) 
print ("{0} mins down each column" .format(m.min(axis = 0)))
print ("{0} mins across each row" .format(m.min(axis = 1)))
print ("{0} max down each column" .format(m.max(axis = 0)))

10 min of the entire matrix
18 max of entire matrix
0 position of the min value
8 position of the max value
[10 11 12] mins down each column
[10 13 16] mins across each row
[16 17 18] max down each column
