# Linear Algebra

Like matrix multiplication,decompositions, determinants,and other square matrix math, is an important part of any array library.
Unlike some languages like MATLAB,multiplying two two-dimensional arrays with sign is an element-wise product instead of a matrix
dot product.Thus,there is an function dot,both an array method and a function in the numpy namespace,for matrix multiplication.

In [3]:
import numpy as np

In [4]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [5]:
y = np.array([[6.,23.],[-1,7],[8,9]])
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

Note:
    to multiply two matrics (element wise multiplication or mirror multiplication) both matrix must have same shape.

In [6]:
x*y

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [7]:
z = np.arange(6).reshape(2,3)
z

array([[0, 1, 2],
       [3, 4, 5]])

In [8]:
x*z

array([[ 0.,  2.,  6.],
       [12., 20., 30.]])

In linear algebra rows of first matrix is multiply by the columns of second matrix and this is only possible when columns of first
 matrix are equal to  the rows of second matrix.

In [ ]:
      (A)                          (B)
                                                 
                                        
    
    4  5  3  1                    0   8   6   5
    
    3  8  5  2                    1   6   7   8
    
    5  6  3  4                    1   0   3   9
    
                                  4   9   0   2 
    
    
    
    shape or order of Matrix A = (r,c)>>>>>(3,4)
    shape or order of Matrix B = (r,c)>>>>>(4,4)
    
    Rule: Col of A == Rows of B
    

In [11]:
# Order of x
x.shape

(2, 3)

In [12]:
# order of y
y.shape

(3, 2)

In [ ]:
# col of x == rows of y
# hence matrix multiplication can be done

In [13]:
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [14]:
np.dot(y,x) # y.y also fulfilling the rule

array([[ 98., 127., 156.],
       [ 27.,  33.,  39.],
       [ 44.,  61.,  78.]])

In [ ]:
# Note:

 it is not necesary if a.b is possible so b.a will be.
    
    np.dot(a,b)
    
    a.dot(b)
    
    a@b
    
    all are same
    

# NumPY.linalg

has a standard set of matrix decompositions and things like invers and determinant.These are impplemented under the hood via the 
industrystandard linear algebra libraries used in other languages like MATLAB and R, such as 
BLAS, LAPACK, or possibly (depending on your NumPY build) the proprietary intel MKL (Math kernel Library):

In [16]:
from numpy.linalg import inv, qr

In [17]:
x = np.array((np.random.randn(5,5)*10),dtype='int32')
x

array([[-14,  -4,  17, -13,  -6],
       [ -8,   6,   5,   1,  -2],
       [-11,  10,  -9,  12,  14],
       [-10,  -7,  -6,   4,   7],
       [-38,  16,  11, -13,   1]])

In [18]:
inv(x)

array([[ 0.02553236, -0.05869836,  0.03287756, -0.05812906, -0.01758496],
       [-0.02375868, -0.00652288,  0.0179645 , -0.06116025,  0.02102099],
       [ 0.11311813,  0.01305842,  0.08273283, -0.05715746, -0.05333178],
       [ 0.00026567,  0.16141479,  0.0061889 ,  0.04062   , -0.04656094],
       [ 0.1095227 , -0.17142178,  0.13230978, -0.07354817, -0.02320709]])

In [ ]:
The expression X.T.dot(X) computes the dot product of x with its transpose X.T.

In [22]:
mat = x.T.dot(x)
mat

array([[1925, -640, -537,  496, -162],
       [-640,  457,   90,  -58,  119],
       [-537,   90,  552, -491, -269],
       [ 496,  -58, -491,  499,  259],
       [-162,  119, -269,  259,  286]])