# Joining Numpy Arrays

In [7]:
# Joining means putting contents of two or more arrays in a single array.In SQL we join tables based on a key,whereas in Numpy we join  arrays by axes.
# we pass a sequence of arrays that we want to join to the concatenate()function,along with the axis.If axis is not explicitly passed,it is taken an as 0.

# join two arrays

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1,arr2))

print(arr)

[1 2 3 4 5 6]


In [3]:
# Join two 2-D arrays along rows(axis = 1):

arr1 = np.array([[1, 2],[3, 4]])

arr2 = np.array([[5, 6],[7, 8]])

arr = np.concatenate((arr1,arr2,), axis = 1)
print(arr)


[[1 2 5 6]
 [3 4 7 8]]


# Joining Arrays Using Stack Functions:


In [4]:
# Stacking is same as concatenation,the only difference is that stacking is done along a new axis.
# we can concatenate two 1-D arrays along the sexond axis which woulds result in putting them one over the other,ie.stacking.
# we pass a sequence of arrays that we want to join to the stack() method along with the axis.If axis is not explicitly passed it is taken as 0.

import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([2, 4, 6])

arr = np.stack((arr1,arr2),axis = 1)

print(arr)

[[1 2]
 [2 4]
 [3 6]]


# Stacking Along Rows

In [1]:
# Numpy provides a helper function: hstack() to stack along rows.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1,arr2))

print(arr)


    

[1 2 3 4 5 6]


# Stacking Along Columns

In [8]:
# Numpy provides a helper function: vstack() to stack along columms.
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1,arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


# Stacking Along Height(depth)


In [9]:
# Numpy provides a helper function: dstack() to stack along height,which is the same as depth.

import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1,arr2))
print(arr)

[[[1 4]
  [2 5]
  [3 6]]]
