NumPY ufuncs

In [2]:
import numpy as np
x = [1,2,3,4]
y = [4,5,6,7]
z = np.add(x,y)
print(z)

[ 5  7  9 11]


In [4]:
def myadd(x,y):
    return x+y

myadd = np.frompyfunc(myadd, 2, 1)
print(myadd([1,2,3,4],[5,6,7,8]))

[6 8 10 12]


In [10]:
arr1 = np.array([10,20,34,55])
arr2 = np.array([21,5,55,77])
newarr = np.divide(arr1,arr2)
print(newarr)

[0.47619048 4.         0.61818182 0.71428571]


In [ ]:
add(), subtract(), multiply(), mode(), remainder(), divmod() , power(), divide(), absolute()

In [11]:
arr = np.arange(1,10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [14]:
arr = np.arange(1,10)
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [18]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.sum([arr1,arr2])
print(arr3)

21


In [19]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.sum([arr1,arr2],axis =1)
print(arr3)

[ 6 15]


In [20]:
arr = np.array([1,2,3])
newarr = np.cumsum(arr)
print(newarr)

[1 3 6]
