# Basic Indexing and Slicing

In [ ]:
 # Numpy array indexing is a rich topic, as there are many ways you may want to select a subset of yours data or individual elements.One-dimensional arrays are simple; on the surface they act similarly to python list:

In [6]:
import numpy as np

In [7]:
arr = np.arange(10)

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr[5]

5

In [10]:
arr[5:8]

array([5, 6, 7])

In [11]:
arr[5:8] = 12

In [12]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [13]:
 #As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated(or broadcasted henceforth) to the entire selection.An important first distinctinon from python's build-in lists is that array slices are views on the original array.This means that the data is not copied, and any modifications to the view will be reflected in the source array.
# To give an example of this,I first create a slice of arr:

In [14]:
arr_slice = arr[5:8]

In [15]:
arr_slice

array([12, 12, 12])

In [16]:
# Now, when I change values in arr_slice, the  mutations are reflected in the original array arr:

In [17]:
arr_slice[1] = 12345

In [18]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [19]:
# The "bare" slice [:] will assign to all values in an array:

In [20]:
arr_slice[:] = 64

In [21]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [22]:
# If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array__ for example, arr[5:8].copy().

In [23]:
# with higher dimensional,you have many more options.In a two-dimensional array,elements at each index are no longer scalars but rather one-dimensional arrays:

In [24]:
arr2d = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])

In [25]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr2d[2]

array([7, 8, 9])

In [ ]:
Thus, individual elements can be accessed recursively.But that is a bit too much work,so you can pass a comma-separated list of indices to select individual elements.so these are equivalent:

In [28]:
arr2d[0][2]

3

In [29]:
arr2d[0,2]

3

In [ ]:
# In multidimentional arrays,if you omit later indices,the returned object will be a lower dinemsional ndarray consisting of all the data along the higher dimensions.so in the 2*2*3 array arr3d:

In [57]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [58]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [59]:
arr3d.ndim

3

In [60]:
# arr3d[0] is a 2*3 array:

In [61]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [62]:
# both scalar values and arrays can be assigned to arr3d[0]:

In [63]:
old_values =  arr3d[0].copy()

In [64]:
arr3d[0] = 35

In [65]:
arr3d

array([[[35, 35, 35],
        [35, 35, 35]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [66]:
arr3d[0] = old_values

In [67]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
# similarly, arr3d[1, 0] gives you all of the values whose indices start with(1, 0) forming a I-dimensional array:

In [68]:
arr3d[1, 0]

array([7, 8, 9])

In [ ]:
# This expression is the same as though we had indexed in two steps:

In [69]:
x =  arr3d[1]

In [70]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [71]:
x[0]

array([7, 8, 9])

In [ ]:
# Note that in all of these cases where subsections of the array have been seleted, the returned arrays are views.

# Indexing with slices

In [ ]:
# Like one-dimensional objects such as python lists, ndarrays can be sliced with the familiar syntax:

In [72]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [73]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [ ]:
# Consider the two-dimensional array from before,arr2d.Slicing this array is a bit differenct:

In [74]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [75]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
# As you can see, it has sliced along axis 0, the first axis,A slice, therefore, selects a range of elements along an axis.It can be helful to read the expression arr2d[:2] as "select the first two rows of arr2d".
# you can pass multiple slices just like you can pass multiple indexes:

In [76]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [78]:
arr2d[1, :2]

array([4, 5])

In [79]:
arr2d[:2, 2]

array([3, 6])

In [80]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [81]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [82]:
arr2d[:2, 1:] = 0

In [83]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [ ]:
Note that a colon by itselg means to take the entire adis, so you can slice only higher dimensional axes by doing: Of course, assigning to a slice expression assigns to the whole selection: