In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Creating the an array using numpy

In [5]:
import numpy as np

In [6]:
food = np.array(["pakora","samosa","Raita"])
food

array(['pakora', 'samosa', 'Raita'], dtype='<U6')

In [8]:
price = np.array([5,5,5])
price

array([5, 5, 5])

In [9]:
type(price)

numpy.ndarray

In [10]:
type(food)

numpy.ndarray

In [11]:
len(food)

3

In [12]:
price[2]

5

In [13]:
price[0:]

array([5, 5, 5])

In [14]:
food[1]

'samosa'

In [15]:
price.mean()

5.0

In [16]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [17]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [18]:
# empty
np.empty(5)

array([1., 1., 1., 1., 1.])

In [19]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [21]:
# specific interval
np.arange(2, 20, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [22]:
# table
np.arange(0,50,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [23]:
# table of 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [25]:
# line space
np.linspace(1,100, num=5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [26]:
np.linspace(1,100,num=50)# in this way we can generate random data inside array

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [27]:
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [28]:
#spacify  your data type
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [29]:
np.ones(50, dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Array functions

In [31]:
a = np.array([10,12,15,2,3,4,5,6,100,344,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   3. ,   4. ,   5. ,   6. , 100. ,
       344. ,   0.5,  10.3])

In [33]:
a.sort()
a

array([  0.5,   2. ,   3. ,   4. ,   5. ,   6. ,  10. ,  10.3,  12. ,
        15. , 100. , 344. ])

In [34]:
b = np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [36]:
c=np.concatenate((a,b))
c

array([  0.5,   2. ,   3. ,   4. ,   5. ,   6. ,  10. ,  10.3,  12. ,
        15. , 100. , 344. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [37]:
c.sort()
c

array([  0.5,   2. ,   3. ,   3.4,   4. ,   5. ,   6. ,  10. ,  10.2,
        10.3,  12. ,  15. ,  45.5,  53.6,  91.6, 100. , 344. ])

# 2-D arrays

In [38]:
a = np.array([[1,2,3,4],[5,4,6,7]])
a

array([[1, 2, 3, 4],
       [5, 4, 6, 7]])

In [39]:
b = np.array([[6,7],[8,9]])
b

array([[6, 7],
       [8, 9]])

In [40]:
c= np.concatenate((a,b))
c

ValueError: all the input array dimensions for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [41]:
a = np.array([[1,2,3,4],[5,4,6,7]])
a

array([[1, 2, 3, 4],
       [5, 4, 6, 7]])

In [42]:
b = np.array([[4,5,6,4],[8,9,0,8]])
b

array([[4, 5, 6, 4],
       [8, 9, 0, 8]])

In [45]:
c= np.concatenate((a,b), axis=0)
c

array([[1, 2, 3, 4],
       [5, 4, 6, 7],
       [4, 5, 6, 4],
       [8, 9, 0, 8]])

In [46]:
c= np.concatenate((a,b), axis=1)
c

array([[1, 2, 3, 4, 4, 5, 6, 4],
       [5, 4, 6, 7, 8, 9, 0, 8]])

In [49]:
 a = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],
               
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],
               
                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]]])
a

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [53]:
# to din the number of dimensions
a.ndim

3

In [54]:
b= np.array([[5,6,7],
            [8,9,10],
            [10,11,12,]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [55]:
b.ndim

2

In [56]:
# size (number of elements)
a.size

24

In [57]:
a.shape

(3, 2, 4)

In [58]:
a =np.arange(7)
a

array([0, 1, 2, 3, 4, 5, 6])

In [59]:
# reshape
a=a.reshape(3,2)
a

ValueError: cannot reshape array of size 7 into shape (3,2)

In [60]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [62]:
b=a.reshape(3,3)
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [63]:
# reshape
np.reshape(a, newshape=(1,9), order='c')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [65]:
# convert 1D into 2D
a = np.array([1,2,3,4,5,6,7,8,9])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a.shape

(9,)

In [70]:
# row wise
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [68]:
b.shape

(1, 9)

In [72]:
# column wise
c= a[:, np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [73]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
a[2:6]

array([3, 4, 5, 6])

In [75]:
a[2:9]

array([3, 4, 5, 6, 7, 8, 9])

In [76]:
a*6

array([ 6, 12, 18, 24, 30, 36, 42, 48, 54])

In [77]:
a+6

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [78]:
a.sum()

45

In [80]:
a.mean()

5.0