# DIFFICULTY LEVEL BIGINER

In [13]:
import numpy as np # import the numpy package under the name np.

In [19]:
#create a null vector of size 10
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
# Create a vector with values ranging from 10 to 49.
arr1 = np.array(range(10,49))
arr1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

In [31]:
# Find the shape of previous array in questions 3.
np.shape(arr1)

(39,)

In [33]:
# print the type of the previous arange in question 3.
arr1.dtype

dtype('int32')

In [67]:
# print the version of the arrray in questions 3.
import numpy as np
print(np.__version__)

1.18.1


In [34]:
# Print the dimenstion of the array in question 3.
arr1.ndim

1

In [69]:
# create the boolean array with all the True values.
import numpy as np
arr = np.array([2 ,4, 6, 8, 10])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[ True  True  True  True  True]
[ 2  4  6  8 10]


In [35]:
# Create a two dimension array.
d2 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
d2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [42]:
# Create a three dimenstion array.
d3 = np.array([[[1, 2, 3],[4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])
d3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

# DIFFICULTY LEVEL EASY

In [56]:
# Create a 3*3 identity matric
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [58]:
arr = np.array([1, 2, 3, 4, 5]) # convert the data type of the given array from into float.

In [60]:
newarr = arr.astype('f')
print(newarr)

[1. 2. 3. 4. 5.]


In [58]:
# Multiply arr1 with arr2.
arr1 = np.array([[1., 2., 3.],[4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr3 = np.multiply(arr1,arr2)
print(arr3)

[[ 0.  8.  3.]
 [28. 10. 72.]]


In [70]:
# Extract all odd numbers from array with values(0-9)
a = np.array(range(0,9))
a[a%2 == 1]

array([1, 3, 5, 7])

In [81]:
# Replace all odd numbers to -1 from previous array.
x = np.array([0,1,2,3,4,5,6,7,8,9])
odd_values = (x%2 == 1)
x[odd_values] = -1
print(x)

[ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [8]:
# Reverse a vector(first element becomes last)
arr = np.array([4, 3, 0, 2, 1])
print(np.sort(arr))

[0 1 2 3 4]


In [10]:
# create a null vector of size 10 but the fifth value which is 1.
d1 = np.array([4, 5, 6, 7, 1, 2, 3, 8, 9, 0])
d1

array([4, 5, 6, 7, 1, 2, 3, 8, 9, 0])

In [74]:
# Make an array by comparing both the arrays provided above
arr1 = np.array([[1.,2.,3.],[4.,5.,6.,]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
diffs = arr1 - arr2
print(diffs)

[[ 1. -2.  2.]
 [-3.  3. -6.]]


In [28]:
arr = np.arange(10) # Replace the values of indexes 5,6,7 and 8 to 12
arr[5:9] = 12
print(arr)

[ 0  1  2  3  4 12 12 12 12  9]


In [77]:
# Create a 2d array with 1 on the border and 0 inside
import numpy as np
x = np.ones((5,5))
print("original array:")
print(x)
print(("1 on the border  and 0 inside in the array"))
x[1:-1, 1:-1] = 0
print(x)


original array:
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
1 on the border  and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# DIFFICULTY LEVEL MEDIUM

In [25]:
arr2d = np.array([[1, 2, 3],[4, 5, 6,],[7, 8, 9]]) # replace the value 5 to 12
arr2d[1,1] = 12
print(arr2d)

[[ 1  2  3]
 [ 4 12  6]
 [ 7  8  9]]


In [32]:
# convert all the values of 1st array to 64
arr3d = np.array([[[1, 2, 3],[4, 5, 6]],[[7, 8, 9],[10, 11, 12]]])
arr3d[0] = 64
print(arr3d)

[[[64 64 64]
  [64 64 64]]

 [[ 7  8  9]
  [10 11 12]]]


In [13]:
# Make a 2-Dimensional array with value 0-9 and slice out the first 1st 1-D array from it
arr2d = np.arange(9).reshape(3, 3)
arr2d 

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr2d[0, 0:]

array([0, 1, 2])

In [18]:
# Make a 2-Dimensional array with values 0-9 and sliceout the 2nd value from 2nd 1-D array from it
arr2d = np.arange(9).reshape(3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
arr2d[1,1]

4

In [20]:
# Make a 2-Dimenstional array with values 0-9 and slice out the third column but only the first two rows.
arr2d = np.arange(9).reshape(3,3)
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [24]:
arr2d[0:2, 2]

array([2, 5])

In [78]:
# Find the positions where elements of a and b match
import numpy as np
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

In [35]:
# Create a 10*10 array with random values and find the minimum and maximum
x = np.random.random((10,10))
print("Original Array:")
print(x)
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

Original Array:
[[0.07763491 0.63933294 0.05220383 0.59683484 0.17688336 0.5533275
  0.77819173 0.72101946 0.92216954 0.97330128]
 [0.16657332 0.63568599 0.36149003 0.41862136 0.05398518 0.6315807
  0.5784154  0.61894755 0.44820348 0.19332114]
 [0.60502988 0.89371515 0.5056755  0.72132017 0.34703581 0.51711918
  0.96704117 0.58340216 0.5903397  0.47086599]
 [0.88586393 0.67578431 0.38852058 0.79211554 0.12181787 0.23292564
  0.01953574 0.41333119 0.81230234 0.60378467]
 [0.30715415 0.85530604 0.54298933 0.18127818 0.84958848 0.70528715
  0.66070608 0.32859828 0.25103016 0.72481644]
 [0.61747572 0.65198575 0.93077263 0.74120669 0.65885902 0.25265969
  0.46910604 0.56934976 0.28645049 0.17584067]
 [0.06991741 0.83782934 0.54786544 0.79072554 0.23173605 0.52087347
  0.93444738 0.85609246 0.51408002 0.57288684]
 [0.24033096 0.81974869 0.06931925 0.77536442 0.78716834 0.27699831
  0.67076317 0.97466061 0.57787956 0.82708813]
 [0.00905109 0.04939017 0.96001706 0.25782341 0.74879244 0.9434899

In [36]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# Find the common items between a and b
c = np.intersect1d(a, b)
print(c)

[2 4]


# DIFFICULTY LEVEL HARD

In [6]:
names = np.array(["Bob", "Joe", "Will", "Bob","Will", "Joe","Joe"])
x = np.unique(names)
print(x)
                               

['Bob' 'Joe' 'Will']


In [86]:
# Following is the input numpy array delete column two and insert following new column in its place.
import numpy as np
samplearray = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(samplearray)

[[34 43 73]
 [82 22 12]
 [53 94 66]]


In [52]:
x = np.array([[1.,2.,3.],[4.,5.,6.]])
y = np.array([[6.,23.],[-1,7],[8,9]])
z = np.dot(x,y)
print(z)

[[ 28.  64.]
 [ 67. 181.]]


In [54]:
# Generate a matrix of 20 random values and find its cumulative sum
from numpy import random
x = random.rand(20)
print(x)

[0.46717838 0.43129232 0.05933262 0.9671738  0.33713496 0.25333831
 0.91464493 0.04272518 0.70064796 0.2160432  0.01716838 0.57073528
 0.55316862 0.98560448 0.62362904 0.4788889  0.55186772 0.37014704
 0.74453554 0.579523  ]


In [55]:
arr2= np.cumsum(x)
print(arr2)

[0.46717838 0.8984707  0.95780332 1.92497712 2.26211209 2.51545039
 3.43009533 3.4728205  4.17346846 4.38951166 4.40668004 4.97741532
 5.53058394 6.51618842 7.13981746 7.61870636 8.17057408 8.54072112
 9.28525666 9.86477966]


In [56]:
# Create an array of size 10, and find the square root of every elements in the arrray, if the values less than 0.5, replace then with 0.
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [57]:
sroot = np.sqrt(x)
print(sroot)

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [85]:
# From array a remove all items present in array b.
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
c = np.setdiff1d(a,b)
print(c)

[1 2 3 4]
