# Question:1

In [45]:
# Convert a 1D array to a 2D array with 2 rows?
import numpy as np

arr1= np.array([0,1,2,3,4,5,6,7,8,9])
newarr = arr1.reshape(2,5)

print(newarr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


# Question:2

In [46]:
# How to stack two arrays vertically?

x = np.array([[0,1,2,3,4],[5,6,7,8,9]])
y = np.array([[1,1,1,1,1],[1,1,1,1,1]])

np.vstack((x,y))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

# Question:3

In [47]:
# How to stack two arrays horizontally?

x = np.array([0,1,2,3,4,1,1,1,1,1])
y = np.array([5,6,7,8,9,1,1,1,1,1])
             

np.hstack((x,y))

array([0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1])

# Question:4

In [48]:
# How to convert an array of arrays into a flat 1d array?

arr = np.array([0,1,2,3,4,5,6,7,8,9])
newarr = arr.reshape(5, 2, -1)
print(newarr)

[[[0]
  [1]]

 [[2]
  [3]]

 [[4]
  [5]]

 [[6]
  [7]]

 [[8]
  [9]]]


# Question:5

In [49]:
# How to convert higher dimenstion into one dimension?

arr = np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14]])

newarr = arr.reshape(-1)

print(newarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# Question:6

In [50]:
# Convert one dimension to higher dimesion
arr = np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])

newarr = arr.reshape(5,3)

print(newarr)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# Question:7

In [51]:
# Create 5*5 an array and find the square of an array? 
arr = np.arange(25).reshape(5,5)
print(arr)

np.sqrt(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739],
       [3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949]])

# Question:8

In [52]:
# Create 5*6 an array and find the mean?
arr = np.arange(30).reshape(5,6)
print(arr)

np.mean(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

# Question:9

In [53]:
# Find the standard deviation of the previous array in Q8?
arr = np.arange(30).reshape(5,6)
print(arr)
np.std(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


8.65544144839919

# Question:10

In [54]:
# Find the median of the previous array in Q8?
arr = np.arange(30).reshape(5,6)
print(arr)
np.median(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


14.5

# Question:11

In [55]:
# Find the transpose of the previous array in Q8?
arr = np.arange(30).reshape(5,6)
print(arr)
np.transpose(arr)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

# Question:12

In [56]:
# Create a 4*4 an array and find the sum of diagonal elements?
arr = np.arange(16).reshape(4,4)
print(arr)
np.trace(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


30

# Question:13

In [57]:
# Find the determinant of the previous array in Q12?
arr = np.arange(16).reshape(4,4)
print(arr)
np.trace(arr)

np.linalg.det(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


0.0

# Question:14

In [59]:
# Find the 5th and 95th percentile of an array?
import numpy
ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31]

x = numpy.percentile(ages, 95)
print(x)

80.0


In [60]:
ages = [5,31,43,48,50,41,7,11,15,39,80,82,32,2,8,6,25,36,27,61,31] 

x = numpy.percentile(ages, 5)

print(x)


5.0


# Question:15

In [76]:
# How to find if a given array has any null values?

arr = np.arange(45).reshape(5,9)

np.sum(arr)

990

In [77]:
array_sum = np.sum(arr)
array_has_nan = np.isnan(array_sum)
print(array_has_nan)

False
