# Data Types for ndarrays

In [ ]:
# The data type or dtype is a special object containing the information (or metadata,)data about data)the ndarray needs to interpret
 a chunk of memory as a particular type of data:
        

In [5]:
import numpy as np

In [6]:
arr1 = np.array([1, 2, 3], dtype=np.float64)

In [8]:
arr2 = np.array([1, 2, 3,], dtype=np.int32)

In [9]:
arr1.dtype

dtype('float64')

In [10]:
arr2.dtype

dtype('int32')

In [ ]:
# you can explicitly convert or cast an array from one dtype to another using ndarray's astype method:

In [11]:
arr = np.array([1, 2, 3, 4, 5])

In [12]:
arr.dtype

dtype('int32')

In [13]:
float_arr = arr.astype(np.float64)

In [14]:
float_arr.dtype 

dtype('float64')

In [ ]:
# in this example, integers were cast to floating point. If I cast some floating-point numbers to be of integer dtype,_
# _the decimal part will be truncated:    
    

In [16]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [17]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [19]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [20]:
# if you have an array of strings represting numbers, you can use astype to convert them to numeric form:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [21]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [ ]:
#If casting were to fail for some reaso (like a string that cannot be converted to float64), a valueError will be raised. Here I 
 # was  a bit lazy and wrote float instead of np.float64; Numpy aliases the python types to its own equivalent data dtypes.
# you can also use another array's dtype attribute:

In [23]:
int_array = np.arange(10)

In [24]:
calibers = np.array([.22, .270, .357, .380, .44, .50],dtype=np.float64)

In [25]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# There are shorthand type code strings you can also use to refer to a dtype:

In [26]:
empty_uint32 = np.empty(8, dtype='u4')

In [27]:
empty_uint32

array([4980816, 4259906, 4915267, 5111877, 3997764, 7274605, 7667812,
       6619244], dtype=uint32)

In [ ]:
Calling astype always creates a new array(a copy of the data), even if the new dtype is the same as the old dtype.

# Arithmetic with Numpy Arrays

In [ ]:
# Arithmetic with Numpy Arrays
 # Arrays are important because they enable you to express batch operations on data without writting any for loops. Numpy users
 # call this vectorization. Any arithmetic operations between equal-size arrays applies the operation element-wise:

In [34]:
arr3 = np.array([[1., 2., 3.], [4., 5., 6.]])

In [35]:
arr3

array([[1., 2., 3.],
       [4., 5., 6.]])

In [37]:
arr3 * arr2

array([[ 1.,  4.,  9.],
       [ 4., 10., 18.]])

In [38]:
arr3 - arr2

array([[0., 0., 0.],
       [3., 3., 3.]])

In [ ]:
Arithmetic operations with sclars progagate the scalar argument to each element in the array:

In [39]:
1 / arr3

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [40]:
arr3 ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [ ]:
 # Comparisons between arrays of the same size yield boolean arrays:

In [42]:
arr4 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [43]:
arr4

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [44]:
arr4 > arr3

array([[False,  True, False],
       [ True, False,  True]])

In [ ]:
# Operation between differently sized arrays is called broadcasting.