# Numpy ndarry:A Multidimensional Array Object

In [21]:
import numpy as np

In [22]:
# Generate some random data
data = np.random.randn(2, 3)

In [23]:
data

array([[ 0.59054664, -0.92352503, -1.2001601 ],
       [ 0.10769459,  0.40356342, -0.81485261]])

In [24]:
# I then write mathematical operations With data:

In [25]:
data * 10

array([[  5.90546645,  -9.23525027, -12.00160101],
       [  1.07694592,   4.03563423,  -8.1485261 ]])

In [26]:
data + data

array([[ 1.18109329, -1.84705005, -2.4003202 ],
       [ 0.21538918,  0.80712685, -1.62970522]])

In [27]:
# Every array has a shape, a tuple indicating the size of each dimension, and a dtype,an object describing the data type of the array:
    

In [28]:
data.shape

(2, 3)

In [29]:
data.dtype

dtype('float64')

# creating ndarrays

In [43]:
#The easiest way to create an array is to use the array function.For example,a list is a good candidate for conversion:
data1 = [6, 7, 5, 8.5, 0, 1]

In [44]:
arr1 = np.array(data1)

In [52]:
arr1 #  in array function data elements should be same datatype.if one element is float then other will become the float type

array([6. , 7. , 5. , 8.5, 0. , 1. ])

In [53]:
# Nested sequences, like a list of equal-length lists, will be converted into a multidimensional array:
data2 = [[1, 2, 3, 4],[5, 6, 7, 8]]

In [54]:
arr2 = np.array(data2)

In [55]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [56]:
arr2.shape # Since data2 was  a list of lists, the Numpy array arr2 has two dimensions with shape inferred from the data.we can conform this by inspecting the ndim and shape attributes:

(2, 4)

In [57]:
arr2.ndim

2

In [58]:
arr1.dtype

dtype('float64')

In [59]:
arr2.dtype

dtype('int32')

In [60]:
# In addition to np.array,there are a number fo other functions for creating new arrays. As example, zeros and ones create arrays of 0s or 1s, respectively,with given length or shape.empty creates an array without initializing its values to any particular value.To create a higher dimensional array with these methods, pass a tuple for the shape:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [61]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [68]:
np.empty((2, 3, 2)) # its not safe to assume that np.empty will return an  array of all zeros.In some cases,it may return uninitialized "garbage" values.

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [69]:
# arange is an array-valued version of the built-in Python range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])